# 构建阶段
FROM node:20-alpine AS build
WORKDIR /app
COPY front-end/package*.json ./
RUN npm install
COPY front-end/ ./
RUN npm run build

# 生产阶段
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
